relay:
  upstream: "${SENTRY_WEB_INTERNAL_URL}"
  host: 0.0.0.0
  port: 3000
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "${KAFKA_BROKERS}"}
    - {name: "message.max.bytes", value: 50000000} # 50MB
  redis: "${REDIS_URL}"
  geoip_path: "/geoip/GeoLite2-City.mmdb"

# In some cases, relay might fail to find out the actual machine memory
# therefore it makes the healthcheck fail and events can't be submitted.
# See https://github.com/getsentry/self-hosted/issues/3330 for more details.
# As a workaround, uncomment the following `health` and `spool` sections:
#
# health:
#  max_memory_percent: 1.0
# spool:
#   envelopes:
#     path: "/tmp/relay-spool-envelopes"
#     max_backpressure_memory_percent: 1.0

# If you have statsd server, you can utilize that to monitor self-hosted Relay.
# To start, uncomment the following `metrics` section and adjust the options as needed.
#
# metrics:
#   statsd: "127.0.0.1:8125"
#   prefix: relay
